#!/usr/bin/env python3
"""Render docs/CLAIM_REGISTRY.md and every headline claim count from the
canonical machine-readable registry at docs/claims.yaml.

This exists because a hand-maintained summary reported "1 REJECTED, 4 OCCUPIED,
8 WEAKENED, 1 SUPPORTED_CANDIDATE, 1 UNKNOWN" for 14 claims -- which sums to
15. The real count was 7 WEAKENED. Counts are now derived, never typed.

Any file may embed generated counts by wrapping a region in:

    <!-- CLAIM-COUNTS:BEGIN --> ... <!-- CLAIM-COUNTS:END -->

Usage:
    python3 bibliography/build_claims.py          # render + inject
    python3 bibliography/build_claims.py --check   # verify, non-zero if stale
"""
import argparse
import collections
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CLAIMS = ROOT / "docs" / "claims.yaml"
REGISTRY = ROOT / "docs" / "CLAIM_REGISTRY.md"
BEGIN, END = "<!-- CLAIM-COUNTS:BEGIN -->", "<!-- CLAIM-COUNTS:END -->"
# Files that may embed a generated counts block.
INJECT = ["README.md", "novelty/CURRENT_NOVELTY_VERDICT.md",
          "novelty/SURVIVING_CLAIMS.md", "novelty/ABANDONED_CLAIMS.md",
          "novelty/NOVELTY_TREE.md", "novelty/FINAL_NOVELTY_RESOLUTION.md",
          "tasks/CURRENT.md"]
STATUS_ORDER = ["SUPPORTED_CANDIDATE", "WEAKENED", "OCCUPIED", "REJECTED",
                "UNKNOWN", "NEEDS_FULL_TEXT"]
AXES = [("concept", "Concept"), ("method", "Method"),
        ("empirical", "Empirical"), ("operational_artifact", "Artifact")]


def load():
    doc = yaml.safe_load(CLAIMS.read_text(encoding="utf-8"))
    claims = doc["claims"]
    vocab = set(doc["status_vocabulary"])
    axv = set(doc["axis_vocabulary"])
    bad = [c["claim_id"] for c in claims if c.get("status") not in vocab]
    if bad:
        raise SystemExit(f"status outside vocabulary: {bad}")
    for c in claims:
        for k, v in (c.get("novelty_axes") or {}).items():
            if v not in axv:
                raise SystemExit(f"{c['claim_id']} axis {k}={v} outside vocabulary")
    return doc, claims


def counts_block(claims):
    n = len(claims)
    c = collections.Counter(x["status"] for x in claims)
    parts = [f"{c[s]} {s}" for s in STATUS_ORDER if c[s]]
    total = sum(c.values())
    if total != n:                      # cannot happen, but this file exists because a count was wrong once
        raise SystemExit(f"count mismatch: {total} != {n}")
    lines = [BEGIN,
             f"**{n} registered claims** — " + " · ".join(parts) + f" (sums to {total}).",
             "",
             "| Status | Count |", "|---|---|"]
    lines += [f"| `{s}` | {c[s]} |" for s in STATUS_ORDER if c[s]]
    fam = collections.Counter(x.get("family", "WG-C") for x in claims)
    if len(fam) > 1:
        lines += ["", "| Family | Claims |", "|---|---|"]
        lines += [f"| `{k}` | {v} |" for k, v in sorted(fam.items())]
    lines += ["", "*Generated by `bibliography/build_claims.py` from "
              "`docs/claims.yaml`. Do not hand-maintain these counts.*", END]
    return "\n".join(lines)


def render_registry(doc, claims):
    block = counts_block(claims)
    out = ["# CLAIM_REGISTRY.md", "",
           "**GENERATED** from `docs/claims.yaml` by `bibliography/build_claims.py`.",
           "Edit the YAML, never this file.", "",
           "Every assertion WildfireGuardian might make lives here with an ID and a",
           "status. **If it is not in this registry, it may not be claimed.**", "",
           "Statuses are defined in `docs/NOVELTY_STANDARD.md` §5. `UNKNOWN` is the",
           "default and carries no credit.", "",
           "Each claim also carries a **four-axis novelty score** (concept / method /",
           "empirical / operational artifact). These are scored separately and must not",
           "be collapsed: a dispatch-by algorithm can be methodologically occupied while",
           "a Korean dispatch-by atlas remains empirically open.", "",
           block, "", "---", "", "## Summary table", "",
           "| ID | Claim | Status | Concept | Method | Empirical | Artifact | Threat papers |",
           "|---|---|---|---|---|---|---|---|"]
    for c in sorted(claims, key=lambda x: x["claim_id"]):
        ax = c.get("novelty_axes") or {}
        tp = " ".join(f"`{p}`" for p in (c.get("threat_papers") or [])) or "—"
        out.append("| {} | {} | {} | {} | {} | {} | {} | {} |".format(
            c["claim_id"], c.get("short", ""), c["status"],
            *[ax.get(k, "—") for k, _ in AXES], tp))

    out += ["", "---", "", "## Full records", ""]
    for c in sorted(claims, key=lambda x: x["claim_id"]):
        out += [f"### {c['claim_id']} — {c.get('short','')}", "", "```yaml",
                yaml.safe_dump(c, sort_keys=False, allow_unicode=True, width=100).rstrip(),
                "```", ""]
    return "\n".join(out) + "\n"


def inject(text, block):
    if BEGIN not in text:
        return text, False
    pre = text.split(BEGIN)[0]
    post = text.split(END, 1)[1] if END in text else ""
    new = pre + block + post
    return new, new != text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    doc, claims = load()
    rendered = render_registry(doc, claims)
    block = counts_block(claims)

    stale = []
    if REGISTRY.read_text(encoding="utf-8") != rendered:
        stale.append(str(REGISTRY.relative_to(ROOT)))
        if not args.check:
            REGISTRY.write_text(rendered, encoding="utf-8")

    for rel in INJECT:
        p = ROOT / rel
        if not p.exists():
            continue
        new, changed = inject(p.read_text(encoding="utf-8"), block)
        if changed:
            stale.append(rel)
            if not args.check:
                p.write_text(new, encoding="utf-8")

    n = len(claims)
    c = collections.Counter(x["status"] for x in claims)
    print(f"{n} claims: " + ", ".join(f"{c[s]} {s}" for s in STATUS_ORDER if c[s]))
    if args.check:
        if stale:
            print("STALE (run without --check):", ", ".join(stale))
            return 1
        print("all generated files up to date")
        return 0
    print("updated:", ", ".join(stale) if stale else "nothing (already current)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
